extends:
  [
    'stylelint-config-standard',
    'stylelint-config-prettier',
    'stylelint-prettier/recommended',
  ]

rules:
  at-rule-no-unknown:
    [
      true,
      'ignoreAtRules':
        ['extends', 'apply', 'tailwind', 'components', 'utilities', 'screen'],
    ]
